version: "3.8"

# networks:
#   service_client:
#     name: client_api
#     external: true
#     driver: bridge

services:  
  portal-app:
    container_name: portal-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true      
    environment:
      - REACT_APP_URL=http://localhost:85
    # networks:
    #  - service_client